// <auto-generated />
namespace Frontek_Full_Web_E_Commerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Tarjeta : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tarjeta));
        
        string IMigrationMetadata.Id
        {
            get { return "202602251926377_Tarjeta"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
